version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s.%(msecs)03d  [%(levelname)-5.5s] [%(name)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout # sys.stderr
  file:
    class: logging.handlers.RotatingFileHandler # Example: Use rotating files
    level: INFO
    formatter: standard
    filename: logs/app.log # Base filename, will be timestamped by setup_logging
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: utf8
    # Consider logging.handlers.TimedRotatingFileHandler for date-based rotation

loggers:
  "": # Root logger
    handlers: [console, file]
    level: INFO
    propagate: false # Prevent root logger messages duplicating if other loggers are defined
  # src.services:
  #   handlers: [console, file]
  #   level: DEBUG
  #   propagate: false
